services:
  frontend:
    build: .
    container_name: url-shortner-frontend-vite
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
    environment:
      - VITE_HOST=0.0.0.0
    command: npm run dev -- --host
